# 1.Basic Operations

In [ ]:
# First of all, basic jupyter notebook's operation
# Comments
# Indentations!!!

In [ ]:
# int/float addition
#2 + 3
#2.0 + 3.0
#2.0 + 3

In [ ]:
# string operations
#"hello "
#'hello'
#"hello " + "world!"
#"This is s" + "o"*10 + " cool"

In [6]:
"This is s" + "o"*10 + " cool"

'This is soooooooooo cool'

In [ ]:
# cast
#int("123")
#float(123)
#str(123)

# 2.Variables

In [ ]:
# No type declaration
#x = 2
#x = 3(jupyter RAM issue)
#y = "a string"
#z = 1 + ""

In [15]:
x = 3

y = x + 4

s = "so "

t = "Kaggle is " + s * y + "much fun" + "!" * x

# 3.Data Structures

In [21]:
# string, list, dictionary, set
st = "hello"
l = [1,2,3,4]
d = {"1st": 1, "2nd": 2}
s = set()

In [43]:
# len, index(+,-), add (for loop to access for set), sequences can be cast to list


In [45]:
l

[1, 2, 3, 4, 5]

In [ ]:
# slicing
#l[start(in):stop(ex):step]
#l[1:]
#l[:-1]
#l[0:len(l):2]
#l[1:2] = [6,7,8]

In [50]:
l[1:2] = [6,7,8]

In [51]:
l

[1, 6, 7, 8, 3, 4, 5]

In [ ]:
# in
#'h' in st
#1 in l
#1000 in l
#'1st' in d

# 4.Statements

In [57]:
# if---elif---else
x = 2
if x > 2:
    print(3)
elif x == 2:
    print(2)
else:
    print(1)

2


In [61]:
# while
i = 1
while i < 4:
    print(i)
    break
    i += 1 # no i++

1


In [64]:
for elmt in s:
    print(elmt)

1
your_element


In [62]:
# for loop
for each in d:
    print(each)

1st
2nd
new_key


In [65]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [66]:
d

{'1st': 1, '2nd': 2, 'new_key': 'new_value'}

In [67]:
for key,value in d.items():
    print(key + ' ' + str(value))

1st 1
2nd 2
new_key new_value


In [68]:
l

[1, 6, 7, 8, 3, 4, 5]

In [70]:
for idx,v in enumerate(l):
    print('idx: ' + str(idx) + ' value: ' + str(v))

idx: 0 value: 1
idx: 1 value: 6
idx: 2 value: 7
idx: 3 value: 8
idx: 4 value: 3
idx: 5 value: 4
idx: 6 value: 5


In [ ]:
# The output should be:
a = [1,4,9,16,25,36]

In [72]:
# write a for loop to square every elmt in a list
a = [1,2,3,4,5,6]

In [73]:
for i,d in enumerate(a):
    a[i] = d*d
a

[1, 4, 9, 16, 25, 36]

In [74]:
# list comprehension
a = [1,2,3,4,5,6]
a = [x*x for x in a]

In [75]:
a

[1, 4, 9, 16, 25, 36]

In [76]:
# add if statement
a = [1,2,3,4,5,6]
b = [x for x in a if x < 5]
b

[1, 2, 3, 4]

In [81]:
# more list comprehension
c = [[1,2,3],[4,5,6],[7,8,9]]
import numpy as np
np.array(c)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
(0, [1,2,3]), (1, [4,5,6]), (2, [7,8,9])
for i,d in enumerate(c):
    for j,v in enumerate(d):
        c[i][j] = v*v
c

[[1, 4, 9], [16, 25, 36], [49, 64, 81]]

In [82]:
# how to square every elmt in matrix c?
d = [[x*x for x in each_row] for each_row in c]

In [83]:
d

[[1, 4, 9], [16, 25, 36], [49, 64, 81]]

In [84]:
# functions
def func(arg):
    print(arg)
    print(type(arg))

In [85]:
func("1")

1
<class 'str'>


In [87]:
# pass
def random_func():
    pass

In [88]:
# function that returns a function
def top(x):
    def inner(y):
        return x+y
    return inner

In [89]:
f = top(5)

In [91]:
#f
def f(y):
    return 5+y

f = lambda y: 5+y

f(3)

8

In [ ]:
lambda arguments: expression

In [92]:
# lambda function
# lambda arguments: expression
def top(x):
    return lambda y: x+y

In [93]:
g = top(5)

In [94]:
g(3)

8

# 5.Import/Useful libraries

In [98]:
import math
from math import pi

In [99]:
pi

3.141592653589793

In [101]:
import numpy as np
import pandas as pd
from collections import defaultdict

In [ ]:
# dict with default values
a = defaultdict(list)

In [103]:
# why need default value?
x = dict()
for i in range(5):
    if 'key' not in x:
        x['key'] = list()
    else:
        x['key'].append(i)

In [104]:
x

{'key': [1, 2, 3, 4]}

In [105]:
# why need default value?
x = defaultdict(list)
for i in range(5):
    x['key'].append(i)

In [106]:
x

defaultdict(list, {'key': [0, 1, 2, 3, 4]})

In [107]:
# sort in place
l = [6,5,3,1]
l.sort()

In [108]:
l

[1, 3, 5, 6]

In [109]:
l = [6,5,3,1]
sort_l = sorted(l)

In [110]:
print(l)
print(sort_l)

[6, 5, 3, 1]
[1, 3, 5, 6]


In [ ]:
# sort dictionary


In [ ]:
#sorted(iterable, key[optional], reverse=True/False[optional])

In [ ]:
a = {'2':6, '1':4, '3':2}

In [ ]:
sorted()

In [ ]:
# numpy!

In [117]:
a = np.array([4,3,6])

In [112]:
np.zeros((3,3))
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [113]:
b = np.random.rand(3,3)

In [114]:
b

array([[ 0.37118292,  0.48553987,  0.2026333 ],
       [ 0.99923606,  0.61562309,  0.17381879],
       [ 0.02323343,  0.73777045,  0.42577993]])

In [116]:
b[1,:]

array([ 0.99923606,  0.61562309,  0.17381879])

In [ ]:
np.max, np.min, np.dot, np.vstack

In [118]:
np.vstack((a,b))

array([[ 4.        ,  3.        ,  6.        ],
       [ 0.37118292,  0.48553987,  0.2026333 ],
       [ 0.99923606,  0.61562309,  0.17381879],
       [ 0.02323343,  0.73777045,  0.42577993]])