# 1.Basic Operations

In [1]:
# First of all, basic jupyter notebook's operation
# Comments
# Indentations!!!

In [2]:
# int/float addition
print(2 + 3)
print(2.0 + 3.0)
print(2.0 + 3)

5
5.0
5.0


In [3]:
# string operations
"hello" # double quote declaration
'hello' # single quote declaration
"hello " + "world!" # concatenation
"This is s" + "o"*10 + " cool" # concatenation

'This is soooooooooo cool'

In [4]:
# cast
int("123")
float(123)
str(123)

'123'

# 2.Variables

In [5]:
# No type declaration
x = 2
y = "a string"
z = str(1) + ""

In [6]:
x = 3

y = x + 4

s = "so "

t = "Kaggle is " + s * y + "much fun" + "!" * x

In [7]:
print(t)

Kaggle is so so so so so so so much fun!!!


# 3.Data Structures

In [8]:
# string, list, dictionary, set
st = "hello"
l = [1,2,3,4]
d = {"1st": 1, "2nd": 2}
s = set()

In [9]:
# len, index(+,-), add (for loop to access for set), sequences can be cast to list

In [10]:
l

[1, 2, 3, 4]

In [11]:
# slicing
# l[start(in):stop(ex):step]
l[1:]
l[:-1]
l[0:len(l):2]
l[1:2] = [6,7,8]

In [12]:
l[1:2] = [6,7,8]

In [13]:
l

[1, 6, 7, 8, 7, 8, 3, 4]

In [14]:
# in
'h' in st
1 in l
1000 in l
'1st' in d

True

# 4.Statements

In [15]:
# if---elif---else
x = 2
if x > 2:
    print(3)
elif x == 2:
    print(2)
else:
    print(1)

2


In [16]:
# while
i = 1
while i < 4:
    print(i)
    break
    i += 1 # no i++

1


In [17]:
for elmt in s:
    print(elmt)

In [18]:
# for loop
for each in d:
    print(each)

1st
2nd


In [19]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [20]:
d

{'1st': 1, '2nd': 2}

In [21]:
for key,value in d.items():
    print(key + ' ' + str(value))

1st 1
2nd 2


In [22]:
l

[1, 6, 7, 8, 7, 8, 3, 4]

In [23]:
for idx,v in enumerate(l):
    print('idx: ' + str(idx) + ' value: ' + str(v))

idx: 0 value: 1
idx: 1 value: 6
idx: 2 value: 7
idx: 3 value: 8
idx: 4 value: 7
idx: 5 value: 8
idx: 6 value: 3
idx: 7 value: 4


In [24]:
# write a for loop to square every elmt in a list
a = [1,2,3,4,5,6]

In [25]:
for i,d in enumerate(a):
    a[i] = d*d
a

[1, 4, 9, 16, 25, 36]

In [26]:
# list comprehension
a = [1,2,3,4,5,6]
a = [x*x for x in a]

In [27]:
a

[1, 4, 9, 16, 25, 36]

In [28]:
# add if statement
a = [1,2,3,4,5,6]
b = [x for x in a if x < 5]
b

[1, 2, 3, 4]

In [29]:
# more list comprehension
c = [[1,2,3],[4,5,6],[7,8,9]]
import numpy as np
np.array(c)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
# square every elmt in the matrix c
for i,d in enumerate(c):
    for j,v in enumerate(d):
        c[i][j] = v*v
c

[[1, 4, 9], [16, 25, 36], [49, 64, 81]]

In [31]:
# how to square every elmt in matrix c?
c = [[1,2,3],[4,5,6],[7,8,9]]
d = [[x*x for x in each_row] for each_row in c]

In [32]:
d

[[1, 4, 9], [16, 25, 36], [49, 64, 81]]

In [33]:
# functions
def func(arg):
    print(arg)
    print(type(arg))

In [34]:
func("1")

1
<class 'str'>


In [35]:
# pass
def random_func():
    pass

In [36]:
# function that returns a function
def top(x):
    def inner(y):
        return x+y
    return inner

In [37]:
f = top(5)

In [38]:
#f
def f(y):
    return 5+y

f = lambda y: 5+y

f(3)

8

In [39]:
# lambda function--->  lambda arguments: expression

In [40]:
# lambda function
# lambda arguments: expression
def top(x):
    return lambda y: x+y

In [41]:
g = top(5)

In [42]:
g(3)

8

# 5.Import/Useful libraries

In [43]:
import math
from math import pi

In [44]:
pi

3.141592653589793

In [45]:
import numpy as np
import pandas as pd
from collections import defaultdict

In [46]:
# dict with default values
a = defaultdict(list)

In [47]:
# why need default value?
x = dict()
for i in range(5):
    if 'key' not in x:
        x['key'] = list()
    else:
        x['key'].append(i)

In [48]:
x

{'key': [1, 2, 3, 4]}

In [49]:
# why need default value?
x = defaultdict(list)
for i in range(5):
    x['key'].append(i)

In [50]:
x

defaultdict(list, {'key': [0, 1, 2, 3, 4]})

In [51]:
# sort in place
l = [6,5,3,1]
l.sort()

In [52]:
l

[1, 3, 5, 6]

In [53]:
l = [6,5,3,1]
sort_l = sorted(l)

In [54]:
print(l)
print(sort_l)

[6, 5, 3, 1]
[1, 3, 5, 6]


In [55]:
# sort dictionary
# sorted(iterable, key[optional], reverse=True/False[optional])

In [56]:
a = {'2':6, '1':4, '3':2}

In [57]:
# sort a dictionary by values in ascending order
sorted(a.items(), key=lambda x:x[1])

[('3', 2), ('1', 4), ('2', 6)]

In [58]:
# numpy!

In [59]:
a = np.array([4,3,6])

In [60]:
np.zeros((3,3))
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [61]:
b = np.random.rand(3,3)

In [62]:
b

array([[0.71892458, 0.9110953 , 0.13932569],
       [0.63057322, 0.71767547, 0.08893475],
       [0.99534505, 0.11506017, 0.09774457]])

In [63]:
b[1,:]

array([0.63057322, 0.71767547, 0.08893475])

In [64]:
# np.max, np.min, np.dot, np.vstack

In [65]:
np.vstack((a,b))

array([[4.        , 3.        , 6.        ],
       [0.71892458, 0.9110953 , 0.13932569],
       [0.63057322, 0.71767547, 0.08893475],
       [0.99534505, 0.11506017, 0.09774457]])